version: "3.8"
services:
  pg:
    image: postgres:latest
    container_name: pg-local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "XXX"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-local
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin/

volumes:
  pg_data:
  pgadmin_data: